
import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

public class EditItem extends javax.swing.JFrame {

    static String nEditItemUnit;
    public EditItem() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        Toolkit nToolKit=Toolkit.getDefaultToolkit();
        setIconImage(nToolKit.getImage(getClass().getResource("icon/icon.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        nEditItemQtyTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nEditItemTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nEditItemRateTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BILLING MASTER");
        setResizable(false);
        setSize(new java.awt.Dimension(200, 100));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EDIT ITEM DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel3.setLayout(null);

        nEditItemQtyTextField.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        nEditItemQtyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nEditItemQtyTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(nEditItemQtyTextField);
        nEditItemQtyTextField.setBounds(620, 90, 220, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("ITEM QUANTITY");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(620, 60, 130, 17);

        nEditItemTextField.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jPanel3.add(nEditItemTextField);
        nEditItemTextField.setBounds(40, 90, 250, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("ITEM NAME");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(40, 60, 130, 17);

        nEditItemRateTextField.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        nEditItemRateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nEditItemRateTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(nEditItemRateTextField);
        nEditItemRateTextField.setBounds(340, 90, 220, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("ITEM RATE");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(340, 60, 130, 17);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 153, 255));
        jButton1.setText("OK");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(720, 190, 120, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 70, 880, 260);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EDIT BILLING ITEM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Arial", 1, 18), new java.awt.Color(51, 153, 255))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 923, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nEditItemQtyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nEditItemQtyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nEditItemQtyTextFieldActionPerformed

    private void nEditItemRateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nEditItemRateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nEditItemRateTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DecimalFormat nDC=new DecimalFormat("#.00");
        double nItemAmount=Double.parseDouble(nEditItemRateTextField.getText())*Double.parseDouble(nEditItemQtyTextField.getText());
        String nEditData[]={nEditItemTextField.getText(),nEditItemQtyTextField.getText(),nEditItemUnit,nEditItemRateTextField.getText(),nDC.format(nItemAmount)};
        BillingSystem.addRowinTable(nEditData);
        BillingSystem.updateTotal();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void getTableData(String nTdata[])
    {
        
        
        new EditItem().setVisible(true);
        nEditItemTextField.setText(nTdata[0].toString());
        nEditItemQtyTextField.setText(nTdata[1].toString());
        nEditItemUnit=nTdata[2].toString();
        nEditItemRateTextField.setText(nTdata[3].toString());
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private static javax.swing.JTextField nEditItemQtyTextField;
    private static javax.swing.JTextField nEditItemRateTextField;
    private static javax.swing.JTextField nEditItemTextField;
    // End of variables declaration//GEN-END:variables
}
